all:
  children:
    proxmox:
      hosts:
        proxmox01:
          ansible_host: 192.168.2.200
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    vms:
      hosts:
        k8s-manager:
          ansible_host: 192.168.2.139
          ansible_user: heno
          ansible_ssh_pass: "1"
          ansible_become: true
          ansible_become_pass: "1"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
        k8s-worker:
          ansible_host: 192.168.2.140
          ansible_user: heno
          ansible_ssh_pass: "1"
          ansible_become: true
          ansible_become_pass: "1"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
        mariadb:
          ansible_host: 192.168.2.141
          ansible_user: heno
          ansible_ssh_pass: "1"
          ansible_become: true
          ansible_become_pass: "1"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
        redis:
          ansible_host: 192.168.2.142
          ansible_user: heno
          ansible_ssh_pass: "1"
          ansible_become: true
          ansible_become_pass: "1"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
    docker_hosts:
      hosts:
        mariadb:
          ansible_host: 192.168.2.141
          ansible_user: heno
          ansible_ssh_pass: "1"
          ansible_become: true
          ansible_become_pass: "1"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
        redis:
          ansible_host: 192.168.2.142
          ansible_user: heno
          ansible_ssh_pass: "1"
          ansible_become: true
          ansible_become_pass: "1"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password"
